### ISSUE TITLE
[BUG] Color contrast picker consumes significant memory when monitor size is large

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-windows#951]
**Describe the bug**

The color contrast picker maintains copies of a screenshot of the user's desktop. On a multi-monitor system the extra copies can cause a spike in memory usage. We don't see evidence of a leak, but the single spike can cause strain. One user reported out-of-memory crashes in this area (call stacks below). They weren't able to reproduce the crash when we met, perhaps because they were using a different monitor setup the second time and/or they were running other programs concurrently.

#### Memory usage

A screenshot of the desktop is 32 bits * `SystemInformation.VirtualScreen.Height` * `SystemInformation.VirtualScreen.Width` ([VirtualScreen docs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.systeminformation.virtualscreen?view=netframework-4.8#property-value)).

Creating the empty bitmap:

https://github.com/microsoft/accessibility-insights-windows/blob/82e85338c45db8347323b10f607c56a7b151c158/src/AccessibilityInsights.SharedUx/Dialogs/GlobalEyedropperWindow.xaml.cs#L59

[Copying the screen](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics.copyfromscreen?view=netframework-4.8) to the bitmap:

https://github.com/microsoft/accessibility-insights-windows/blob/82e85338c45db8347323b10f607c56a7b151c158/src/AccessibilityInsights.SharedUx/Dialogs/GlobalEyedropperWindow.xaml.cs#L61-L64

Converting the bitmap to an ImageSource for the XAML:

https://github.com/microsoft/accessibility-insights-windows/blob/82e85338c45db8347323b10f607c56a7b151c158/src/AccessibilityInsights.SharedUx/Dialogs/GlobalEyedropperWindow.xaml.cs#L66

https://github.com/microsoft/accessibility-insights-windows/blob/82e85338c45db8347323b10f607c56a7b151c158/src/AccessibilityInsights.SharedUx/Utilities/ExtensionMethods.cs#L283-L292

Each of these steps led to an additional spike in the memory profiler around the same size as the screenshot image. Removing any of these steps (perhaps there's a different way to create the `ImageSource` using the existing bitmap) would help, or revising the workflow to only hold certain parts of the screen at once.

#### Crash report
A user reported that the app crashes for them in the color-contrast view after a few minutes. They sent us the following event logs:

<details>
<p>

```c#
Application: AccessibilityInsights.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.ExternalException
   at System.Drawing.Bitmap.GetHbitmap(System.Drawing.Color)
   at System.Drawing.Bitmap.GetHbitmap()
   at AccessibilityInsights.SharedUx.Utilities.ExtensionMethods.ConvertToSource(System.Drawing.Bitmap)
   at AccessibilityInsights.SharedUx.Dialogs.GlobalEyedropperWindow.CaptureScreenshot()
   at AccessibilityInsights.SharedUx.Dialogs.GlobalEyedropperWindow..ctor(AccessibilityInsights.SharedUx.ViewModels.ColorContrastViewModel, Boolean, Boolean, System.Action`2<System.Object,System.EventArgs>)
   at AccessibilityInsights.SharedUx.Controls.TestTabs.ColorContrast.Chooser_ColorPickerClicked(System.Object, AccessibilityInsights.SharedUx.Controls.SourceArgs)
   at AccessibilityInsights.SharedUx.Controls.ColorChooser.colorPicker_Click(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at AccessibilityInsights.App.Main()


```

</details>
</p>

<details>
<p>

```c#
Application: AccessibilityInsights.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at System.Windows.Interop.InteropBitmap..ctor(IntPtr, IntPtr, System.Windows.Int32Rect, System.Windows.Media.Imaging.BitmapSizeOptions, MS.Internal.WICBitmapAlphaChannelOption)
   at System.Windows.Interop.Imaging.CriticalCreateBitmapSourceFromHBitmap(IntPtr, IntPtr, System.Windows.Int32Rect, System.Windows.Media.Imaging.BitmapSizeOptions, MS.Internal.WICBitmapAlphaChannelOption)
   at AccessibilityInsights.SharedUx.Utilities.ExtensionMethods.ConvertToSource(System.Drawing.Bitmap)
   at AccessibilityInsights.SharedUx.Dialogs.GlobalEyedropperWindow.CaptureScreenshot()
   at AccessibilityInsights.SharedUx.Dialogs.GlobalEyedropperWindow..ctor(AccessibilityInsights.SharedUx.ViewModels.ColorContrastViewModel, Boolean, Boolean, System.Action`2<System.Object,System.EventArgs>)
   at AccessibilityInsights.SharedUx.Controls.TestTabs.ColorContrast.Chooser_ColorPickerClicked(System.Object, AccessibilityInsights.SharedUx.Controls.SourceArgs)
   at AccessibilityInsights.SharedUx.Controls.ColorChooser.colorPicker_Click(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at AccessibilityInsights.App.Main()

```

</p>
</details>

<details>
<p>

```c#
Application: AccessibilityInsights.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at System.Drawing.Bitmap.GetHbitmap(System.Drawing.Color)
   at System.Drawing.Bitmap.GetHbitmap()
   at AccessibilityInsights.SharedUx.Utilities.ExtensionMethods.ConvertToSource(System.Drawing.Bitmap)
   at AccessibilityInsights.SharedUx.Dialogs.GlobalEyedropperWindow.CaptureScreenshot()
   at AccessibilityInsights.SharedUx.Dialogs.GlobalEyedropperWindow..ctor(AccessibilityInsights.SharedUx.ViewModels.ColorContrastViewModel, Boolean, Boolean, System.Action`2<System.Object,System.EventArgs>)
   at AccessibilityInsights.SharedUx.Controls.TestTabs.ColorContrast.Chooser_ColorPickerClicked(System.Object, AccessibilityInsights.SharedUx.Controls.SourceArgs)
   at AccessibilityInsights.SharedUx.Controls.ColorChooser.colorPicker_Click(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at AccessibilityInsights.App.Main()
```
</p>
</details>

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] 
 - Accessibility Insights for Windows Version:  1.1.1369.1

**Comment by dbjorge** [comment]
The logs definitely suggest an out-of-memory issue. In local testing I do see that invoking the color contrast analyzer causes a large spike in memory usage (from ~100MB to ~250-300MB private set usage), but I don't see obvious evidence of a memory leak just from looking at process explorer.

**That doesn't rule out the possibility of a leak**; we should take a look under a memory profiler, both to look for any leaks and to see if we can identify any low-hanging-fruit for improving memory consumption.

The OOM errors above suggest that it's happening while forming a native bitmap inside this stack:

```
   at System.Drawing.Bitmap.GetHbitmap()
   at AccessibilityInsights.SharedUx.Utilities.ExtensionMethods.ConvertToSource(System.Drawing.Bitmap)
   at AccessibilityInsights.SharedUx.Dialogs.GlobalEyedropperWindow.CaptureScreenshot()
```

It would be good to explore whether there might be options for processing smaller parts of the screen at a time, rather than making giant bitmaps of entire desktops.

**Comment by karanbirsingh** [comment]
An initial look under the VS memory profiler today stayed steady around 180 MB (clicking the eyedropper to get new screenshots every few seconds). I checked that we [delete the GDI bitmap object](https://github.com/microsoft/accessibility-insights-windows/blob/6180882ef2c54af4881d75da9225c72fde2aea63/src/AccessibilityInsights.SharedUx/Utilities/ExtensionMethods.cs#L290) as suggested [here](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.bitmap.gethbitmap?redirectedfrom=MSDN&view=netframework-4.8#System_Drawing_Bitmap_GetHbitmap). I also checked the GDI handle count in Task Manager as suggested [here](https://docs.microsoft.com/en-us/windows/win32/sysinfo/gdi-objects). So far I don't have a repro. I will try to meet with the user who reported this to get more info.

**Comment by karanbirsingh** [comment]
When meeting with the user who reported the OOM crash, they were unable to reproduce it - however, they were working on different monitors. In the meantime we made a fix in #962 to improve the memory usage of automatic-color-contrast. I will update the issue description with more context from the discussion / memory profiling.

**Comment by DaveTryon** [comment]
@karanbirsingh, we decreased memory by 25%. Do you have any suggestions on how we might decrease it further? If not, should we close this out?

**Comment by DaveTryon** [comment]
@karanbirsingh, we discussed this in triage today and concluded that we won't be doing anything else at this time. It's been open for a long time and hasn't gotten any additional hits so we think this is safe, at least until we receive further data that it's a user-impacting problem.
